# Generated by Django 4.2.5 on 2023-12-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('post_content', models.CharField(max_length=500)),
            ],
        ),
    ]
