# Generated by Django 4.2.5 on 2023-12-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_post_images_alter_post_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(max_length=255, upload_to='images/'),
        ),
    ]
